version: '3.9'

services:
  web:
#    build:
#      context: ..
#      dockerfile: ./Dockerfile
    build: .
    restart: on-failure
    env_file:
      - .env
#    expose:
#      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../:/srv/app/
    command: bash -c "python geo_in_terra/manage.py runserver 0.0.0.0:8000"


  db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
      - /usr/local/var/postgres:/var/lib/postgres/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
#    expose:
#      - 5432